# Generated by Django 5.2.4 on 2025-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateCardRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('tier1', 'Issue #1'), ('tier2', 'Deluxe Edition'), ('tier3', 'Collectors Print')], max_length=10)),
                ('amount', models.IntegerField()),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='delegate_payments/')),
                ('user_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('events', models.JSONField(help_text='List of selected events')),
                ('delegate_id', models.JSONField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True)),
                ('payment_screenshot', models.ImageField(upload_to='event_payments/')),
                ('user_id', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=100)),
                ('pass_type', models.CharField(choices=[('sports', 'Nexus Arena (Sports Pass)'), ('cult', 'Nexus Spotlight (Cult Pass)'), ('lit_quiz', 'Nexus Forum - Quiz'), ('lit_lit', 'Nexus Forum - Literary/Debate'), ('lit_premium', 'Nexus Forum - Premium')], max_length=20)),
                ('amount', models.IntegerField()),
                ('user_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='pass_screenshots/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
