# Generated by Django 5.2.4 on 2025-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatecardregistration',
            name='payment_screenshot',
            field=models.ImageField(upload_to='delegate_payments/'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='events',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='passpurchase',
            name='pass_type',
            field=models.CharField(choices=[('sports', 'Sports Pass'), ('cult', 'Cult Pass'), ('lit_quiz', 'Literary Quiz Pass'), ('lit_lit', 'Literary Pass'), ('lit_premium', 'Premium Literary Pass')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passpurchase',
            name='payment_screenshot',
            field=models.ImageField(upload_to='pass_screenshots/'),
        ),
    ]
