# Generated by Django 5.2.4 on 2025-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('pass_type', models.CharField(choices=[('sports', 'Nexus Arena (Sports Pass)'), ('cult', 'Nexus Spotlight (Cult Pass)'), ('lit_quiz', 'Nexus Forum - Quiz'), ('lit_lit', 'Nexus Forum - Literary/Debate'), ('lit_premium', 'Nexus Forum - Premium')], max_length=20)),
                ('amount', models.IntegerField()),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='pass_screenshots/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
